
ARGS:
 video : True
 tab: 'V1_hrnet' 
 dataset: 'pw3d'
 #'mpii,h36m,mpiinf,coco,mpii,lsp,muco,crowdpose'
 GPUS: 4
 distributed_training: False
 model_version: 1
 pretrain: 'imagenet'
 match_preds_to_gts_for_supervision: True
 epoch: 50   ################################ epoch here
 save_visualization_on_img: True

 predict: True
 force_centermap_loss: False
 master_batch_size: -1
 val_batch_size: 1
 val_print_size: 600
 batch_size: 1
 data_slide_len: 8
 nw: 4
 nw_eval: 4
 lr: 0.00005 #0.00005

 fine_tune: False
 fix_backbone_training_scratch: False
 eval: False
 supervise_global_rot: False

 model_return_loss: False
 collision_aware_centermap: True
 collision_factor: 0.2
 homogenize_pose_space: True
 shuffle_crop_mode: True
 shuffle_crop_ratio_2d: 0.1
 shuffle_crop_ratio_3d: 0.4

 merge_smpl_camera_head: False
 head_block_num: 2

 backbone: 'resnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2

 model_path: 'D:/3D/lihaoyuan/vomp/checkpoints/resnet_cm64_V1_hrnet_on_gpu0_val/resnet_cm64_V1_hrnet_val_cache.pkl'
 optim_path:  None #'D:/3D/lihaoyuan/vomp/checkpoints/hrnet_cm64_V1_hrnet_on_gpu0_val/optimizer.npy'

loss_weight:
  MPJPE: 200.
  PAMPJPE: 360.
  P_KP2D: 400.
  Pose: 280. #80
  Shape: 36. # 6
  Prior: 1.6
  CenterMap: 160. # 160

sample_prob:
 h36m: 0.
 mpiinf: 0. # 0.16
 coco: 0.
 lsp: 0.0
 mpii: 0.
 muco: 0.
 crowdpose: 0.

 pw3d: 1. #0.00