
ARGS:
 tab: 'Video_predict'
 video_dataset: 'pw3d'
 GPUS: 0
 predict_video: True
 model_version: 1
 renderer: 'pytorch3d'

 batch_size: 1
 val_batch_size: 8
 data_slide_len: 8
 nw: 3
 fine_tune: True

 backbone: 'hrnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2

 output_html: False
 save_mesh: False # save mesh obj
 save_kp2d: True
 save_centermap: True
 save_dict_results: False
 save_visualization_on_img: True

 model_path: '/data1/lihaoyuan/vomp/checkpoints/hrnet_cm64_no_3dpw_on_gpu4,5_val/hrnet_no_3dpw_video_epoch1.pkl'
 inputs: '/home/lihaoyuan/vomp/ROMP/demo/videos/3dpw.mp4' # None
 output_dir: '/home/lihaoyuan/vomp/ROMP/demo/sample_video_results/'

video_sample_prob:
 pw3d: 1.0



