ARGS:
 tab: 'pw3d_test_train_state'
 # pw3d_test pw3d_pc pw3d_nc pw3d_oc crowdpose_val  crowdpose_test  cmup  MuPoTs  runtime  
 eval_dataset: pw3d_test #'mpiinf_test' 'agora' 'pw3d_test' # mupots pw3d_test  cmup pw3d_nc pw3d_oc
 test_tracking: False
 GPUS: 0
 model_version: 1
 
 pretrain_on_image: False   ####################################
 data_gate: 1
 batch_size: 1  ####################################
 val_batch_size: 8
 data_slide_len: 8  ####################################
 nw_eval: 3
 eval: True
 collision_factor: 0.2
 calc_PVE_error: False
 acquire_pa_trans_scale: False

 backbone: 'hrnet' 
 centermap_size: 64
 centermap_conf_thresh: 0.2
 visualize_all_results: False

#  merge_smpl_camera_head: False
 fine_tune: True

 model_path: '/data1/lihaoyuan/vomp/checkpoints/hrnet_cm64_no_3dpw_on_gpu4,5_val/hrnet_no_3dpw_video_epoch1.pkl'
 output_dir: '/home/lihaoyuan/vomp/ROMP/demo/results/'
 # resnet_on_imgae_epoch_90.pkl
 # resnet_cm64_V1_hrnet_epoch_16.pkl