
### dataset. test_index. video_sample.

ARGS:
 video : True
 tab: 'with_3dpw_sample' 
 video_dataset: 'pw3d' # 'pw3d,h36m' 
 image_dataset: 'mpii,mpiinf,lsp,muco,h36m,pw3d' # 'mpii,mpiinf,muco,lsp,pw3d,crowdpose' 
 # crowdpose  coco(loss nan)
 # h36m,pw3d,mpii,mpiinf,muco,lsp
 GPUS: 4,5
 distributed_training: False
 model_version: 0
 pretrain: 'imagenet'
 match_preds_to_gts_for_supervision: True
 epoch: 40   
 epoch_begin: 0 # 1
 save_visualization_on_img: False  
 eval_datasets: "pw3d" # 'mpiinf','pw3d','pw3d_pc','h36m','mpiinf_test'
 training_sample_3dpw: True

 renderer: 'pytorch3d' # pytorch3d / pyrender

 predict: True
 pretrain_on_image: True
 test_after_pa: False
 rand_crop_enhance: False
 test_interval: 25000 # 7400, 20000
 print_freq: 100 #  100,50
 val_batch_size: 12 # 16
 val_print_size: 50 # 50
 batch_size: 12 #  % GPUs == 0
 data_slide_len: 8 # 2,8
 data_gate: 1 
 nw: 12 # 8 16
 nw_eval: 4 # 4
 lr: 0.00005 #0.00005

 fine_tune: False # True
 master_batch_size: -1
 fix_backbone_training_scratch: False
 eval: False
 supervise_global_rot: False

 model_return_loss: False
 collision_aware_centermap: True
 collision_factor: 0.2
 homogenize_pose_space: False # True
 shuffle_crop_mode: True
 shuffle_crop_ratio_2d: 0.1
 shuffle_crop_ratio_3d: 0.4

 merge_smpl_camera_head: False
 head_block_num: 2

 backbone: 'hrnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2

 model_path: '/data1/lihaoyuan/vomp/checkpoints/hrnet_cm64_without_coord_on_gpu3,4,5_val/hrnet_stage2_epoch2.pkl'
 # '/data1/lihaoyuan/vomp/checkpoints/hrnet_cm64_hrnet_coord_trans_on_gpu4,5_val/hrnet_key_query.pkl'
 # '/data1/lihaoyuan/vomp/checkpoints/hrnet_cm64_hrnet_coord_ori_on_gpu4,5_val/hrnet_epoch_5_onimg.pkl'
 optim_path:  None #'/home/lihaoyuan/vomp/checkpoints/hrnet_cm64_V1_hrnet_on_gpu0_val/optimizer.npy'

loss_weight:
  MPJPE: 200.
  PAMPJPE: 360. #660
  P_KP2D: 400. 
  Pose: 80. #80
  Shape: 36.
  Prior: 1.6
  CenterMap: 160.

  ACCEL: 200.
  A_KP2D: 300.
  Smooth: 100.


video_sample_prob:
 pw3d: 1.0 

# video_sample_prob:
#  h36m: 0.85 
#  pw3d: 0.15 

image_sample_prob:
 mpiinf: 0.2
 lsp: 0.1
 mpii: 0.15
 muco: 0.2 
 h36m: 0.2
 pw3d: 0.15

# image_sample_prob:
#  mpiinf: 0.2
#  lsp: 0.1
#  mpii: 0.1
#  muco: 0.2 
#  h36m: 0.15
#  pw3d: 0.15
#  crowdpose: 0.1

# ps -ef|grep configs_yml=configs/v1.yml|grep -v grep|cut -c 9-15|xargs kill -9
