
### dataset. test_index. video_sample.

ARGS:
 video : True
 tab: 'hrnet_coord_trans' 
 video_dataset: 'pw3d' # 'pw3d,h36m' 
 image_dataset: 'crowdpose' # 'mpii,mpiinf,muco,lsp,pw3d,,crowdpose' 
 # crowdpose  coco(loss nan)
 # h36m,pw3d,mpii,mpiinf,muco,lsp
 GPUS: 4,
 model_version: 1
 pretrain: 'imagenet'
 match_preds_to_gts_for_supervision: True
 epoch: 40   ################################ epoch here
 epoch_begin: 0 # 1
 save_visualization_on_img: False  ##服务器上开不了"
 eval_datasets: "pw3d" # 'mpiinf','pw3d','pw3d_pc','h36m','mpiinf_test'

 renderer: 'pytorch3d' # pytorch3d / pyrender

 predict: True
 pretrain_on_image: False  ###################
 new_training: False
 test_after_pa: False
 rand_crop_enhance: False
 test_interval: 20 # 8000, 2000
 print_freq: 10 #  100,25
 val_batch_size: 8 # 16
 val_print_size: 100 # 50
 batch_size: 4 #  % GPUs == 0
 data_slide_len: 8 # 2,8
 data_gate: 1 
 nw: 4 # 8
 nw_eval: 8 # 4
 lr: 0.00005 #0.00005

 training_test: False ###
 fine_tune: True # True
 master_batch_size: -1
 fix_backbone_training_scratch: False
 eval: False
 supervise_global_rot: False
 calc_PVE_error: True

 model_return_loss: False
 collision_aware_centermap: True
 collision_factor: 0.2
 homogenize_pose_space: False # True
 shuffle_crop_mode: True
 shuffle_crop_ratio_2d: 0.1
 shuffle_crop_ratio_3d: 0.4

 merge_smpl_camera_head: False
 head_block_num: 2

 backbone: 'hrnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2

 model_path: '/data1/lihaoyuan/vomp/checkpoints/hrnet_cm64_with_coord_on_gpu4,5_val/hrnet_with_3dpw_epoch_2.pkl'
 # /data1/lihaoyuan/vomp/checkpoints/hrnet_cm64_no_3dpw_on_gpu4,5_val/hrnet_no_3dpw_video_epoch1.pkl
 # /data1/lihaoyuan/vomp/checkpoints/hrnet_cm64_no_3dpw_on_gpu4,5_val/hrnet_with_3dpw_epoch_2.pkl
 # /data1/lihaoyuan/vomp/checkpoints/hrnet_cm64_no_3dpw_on_gpu4,5_val/hrnet_no_3dpw_image_epoch25.pkl
 optim_path:  None #'/home/lihaoyuan/vomp/checkpoints/hrnet_cm64_V1_hrnet_on_gpu0_val/optimizer.npy'

loss_weight:
  MPJPE: 200.
  PAMPJPE: 360. #660
  P_KP2D: 400. 
  Pose: 80. #80
  Shape: 36.
  Prior: 1.6
  CenterMap: 160.
  ACCEL: 200.
  A_KP2D: 200.
  Smooth: 100.

# loss_weight:
#   MPJPE: 200.
#   PAMPJPE: 360.
#   P_KP2D: 400.
#   Pose: 80. 
#   Shape: 36.
#   Prior: 1.6
#   CenterMap: 160.

# video:80 -- image:170

video_sample_prob:
 pw3d: 1.0 
  # h36m : 1.0

# video_sample_prob:
#  h36m: 0.85 #0.85
#  pw3d: 0.15 #0.15

image_sample_prob:
 crowdpose: 1.0


# ps -ef|grep configs_yml=configs/v1.yml|grep -v grep|cut -c 9-15|xargs kill -9


# ['/data1/lihaoyuan/vomp/dataset/3DPW/imageFiles/outdoors_golf_00/image_00000.jpg']