
ARGS:
 video : True
 tab: 'only_video' 
 video_dataset: 'h36m,pw3d'
 iter_change: 2
 # crowdpose  coco(loss nan)
 # h36m,pw3d,mpii,mpiinf,muco,lsp
 GPUS: 0
 distributed_training: False
 model_version: 1
 pretrain: 'imagenet'
 match_preds_to_gts_for_supervision: True
 epoch: 50   ################################ epoch here
 epoch_begin: 1 # 1
 save_visualization_on_img: False  ##服务器上开不了
 # renderer: 'pyrender' # pytorch3d / pyrender

 predict: True
 test_interval: 30000 # 9000
 print_freq: 50 # 15
 val_batch_size: 7 # 12
 val_print_size: 100 # 50
 batch_size: 7 #  % GPUs == 0
 data_slide_len: 8 #8
 data_gate: 1 
 nw: 3 # 8
 nw_eval: 3 # 4
 lr: 0.00005 #0.00005

 model_save_dir: "/data1/lihaoyuan/vomp/checkpoints/resnet_cm64_only_video_on_gpu0_val/"

 fine_tune: True # True
 fix_backbone_training_scratch: False
 eval: False
 supervise_global_rot: False

 model_return_loss: False
 collision_aware_centermap: True
 collision_factor: 0.2
 homogenize_pose_space: False # True
 shuffle_crop_mode: True
 shuffle_crop_ratio_2d: 0.1
 shuffle_crop_ratio_3d: 0.4

 merge_smpl_camera_head: False
 head_block_num: 2

 backbone: 'resnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2

 model_path: '/data1/lihaoyuan/vomp/checkpoints/resnet_cm64_only_video_on_gpu0_val/resnet_cm64_V1_hrnet_val_cache.pkl'
 # resnet_cm64_V1_hrnet_val_cache.pkl
 # resnet_8to8_cenXst_epoch9.pkl
 optim_path:  None #'/home/lihaoyuan/vomp/checkpoints/hrnet_cm64_V1_hrnet_on_gpu0_val/optimizer.npy'

loss_weight:
  MPJPE: 200.
  PAMPJPE: 360.
  P_KP2D: 400.
  Pose: 280. #80
  Shape: 36. # 6
  Prior: 1.6
  CenterMap: 160. # 160
  Temporal_weight: 20

# video:80 -- image:170
video_sample_prob:
 h36m: 0.85 #0.85
 pw3d: 0.15 #0.15


# ps -ef|grep configs_yml=configs/v1.yml|grep -v grep|cut -c 9-15|xargs kill -9