
ARGS:
 tab: 'process_video'
 gpu: 4,5

 predict: True
 backbone: 'hrnet'
 model_precision: 'fp32'
 val_batch_size: 1
 data_slide_len: 3
 nw: 4
 model_path:  trained_models/vomp_checkpoint_1.pkl #trained_models/ROMP_HRNet32_V1.pkl #
 #模型貌似只能放在 trained_models 下才能读取到
 smpl_mesh_root_align: False
 centermap_conf_thresh: 0.25

 to_frame: False
 make_tracking: False
 temporal_optimization: False
 smooth_coeff: 4.
 show_largest_person_only: False
 show_mesh_stand_on_image: False
 soi_camera: 'far' # 'close' # 'far'
 renderer: 'pytorch3d' # 'pyrender' 'pytorch3d' 

 inputs: 'demo/videos/3dpw.mp4' # None
 output_dir: 'demo/sample_video_results/'
 save_mesh: False
 save_centermap: False
 save_dict_results: True
 save_visualization_on_img: True
 fps_save: 24
 mesh_cloth: 'ghostwhite'  #'LightCyan'